# Generated by Django 5.0.3 on 2024-04-02 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_alter_quiz_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=10800)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 2, 16, 13, 6, 976477)),
        ),
    ]
