# Generated by Django 5.0.3 on 2024-04-02 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_quiz_duration_alter_quiz_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='time',
        ),
        migrations.AddField(
            model_name='quiz',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 2, 17, 20, 28, 78265)),
        ),
        migrations.AddField(
            model_name='quiz',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 2, 17, 20, 28, 78246)),
        ),
    ]
