# Generated by Django 5.0.3 on 2024-04-11 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_remove_quiz_duration_remove_quiz_time_quiz_endtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='integer_answer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single_correct', 'Single Correct'), ('integer_type', 'Integer Type')], default='single_correct', max_length=15),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 15, 41, 47, 334125)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 15, 41, 47, 334105)),
        ),
    ]
